---
- name: Installare i prerequisiti
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
      - docker
    state: present

- name: Abilitare e avviare Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Unire il worker al cluster
  command: kubeadm join <manager_ip>:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash>
